name: Test Setup .NET Action

on:
  workflow_dispatch:

jobs:
  test-dotnet-setup:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Create global.json
      run: |
        dotnet --info
        echo -e "\n======================\n"
        echo "create new global.json"
        dotnet new globaljson --sdk-version 8.0.14 --roll-forward disable
        cat global.json

    - name: Verify .NET version
      run: dotnet --info
